networks:
  app_net:
  users_net:

services:
  users:
    build: ./${CONFIG_PATH}
    container_name: users_service
    ports:
      - "3000:${CONFIG_PORT:-3000}"
    depends_on:
      - users_db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - app_net
      - users_net

  users_db:
    build: ./database/users_db
    container_name: users_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - users_net
